server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://117.72.32.234:3306/flink-cdc-consumer?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zz24270507..

  rabbitmq:
    username: zzz
    password: zzz
    virtual-host: /
    addresses: 117.72.32.234:5672
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual


logging:
  level:
    root: info